---
- name: Install common packages
  hosts: swarm
  roles:
    - common
    - docker

- name: Configure Manager
  hosts: swarm-manager
  roles:
    - dockermanager

- name: Configure Workers
  hosts: swarm-workers
  roles:
    - dockerworkers